# Generated by Django 5.0.2 on 2025-03-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('polynomial', 'Polynomial Regression'), ('knn', 'K-Nearest Neighbors'), ('slr', 'Simple Linear Regression'), ('mlr', 'Multiple Linear Regression'), ('logistic', 'Logistic Regression')], max_length=20)),
                ('input_data', models.JSONField()),
                ('prediction', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
